server:
  port: 8085

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product_service_route
          uri: ${PROJECT_MANAGEMENT_BASE_URL}
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1

        - id: identity_service_route
          uri: ${IDENTITY_SERVICE_URL}
          predicates:
            - Path=/identity/**
          filters:
            - StripPrefix=1

        - id: keycloak_admin_route
          uri: ${KEYCLOAK_BASE_URL}
          predicates:
            - Path=/identity/{realm}/admin/**
          filters:
            - RewritePath=/identity/(?<realm>[^/]+)/admin/(?<segment>.*), /admin/realms/${realm}/${segment}
            - PreserveHostHeader=true

        - id: dynamic_project_route
          uri: ${PROJECT_MANAGEMENT_BASE_URL}
          predicates:
            - Path=/**

logging:
  level:
    root: INFO
    com.paxaris.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
