server:
  port: 8085

project:
  management:
    base-url: ${PROJECT_MANAGEMENT_BASE_URL}
    endpoints:
        web:
          exposure:
            include: health,info


spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product_service_route
          uri: ${PROJECT_MANAGEMENT_BASE_URL}
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1

        - id: identity_service_route
          uri: ${IDENTITY_SERVICE_URL}
          predicates:
              - Path=/identity/**




  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${DUMMY_ISSUER:http://placeholder}

logging:
  level:
    root: INFO
    com.example.gateway: DEBUG

